server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JPOMM/config-data-codigo
          default-label: master
          clone-on-start: true
          force-pull: true
      discovery:
        enable: false

eureka:
  client:
    serviceUrl: 
      defaulZone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: true